### ISSUE TITLE
Unable to read package.json

### ISSUE THREAD

**Issue by erictuvesson** [primer/publish#23]
Hey, It doesn't seem like "--dir" is not working with actions or am I using it wrong?

The package file is at `swagger/generator/package.json`

Action:
```yml
    - name: Publish
      uses: primer/publish@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        args: "--dir=swagger/generator"
```

I have tried to put `--dir=../../swagger/generator` too but it doesn't do any difference.

Action Logs:
```
/usr/bin/docker run --name HIDDEN--label 04bb81 --workdir /github/workspace --rm -e GITHUB_TOKEN -e NPM_AUTH_TOKEN -e args -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/e-commerce-backend/e-commerce-backend":"/github/workspace" HIDDEN
user.email=HIDDEN
user.name=erictuvesson
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/erictuvesson/e-commerce-backend
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
gc.auto=0
[publish] options: {
  "dir": ".",
  "$0": "/primer-publish/cli.js"
}
[publish] npm args: []
/primer-publish/src/context.js:17
    throw new Error(`Unable to read package.json in ${path.join(process.cwd(), dir)}!`)
    ^

Error: Unable to read package.json in /github/workspace!
    at getContext (/primer-publish/src/context.js:17:11)
    at publish (/primer-publish/src/publish.js:15:10)
    at Object.<anonymous> (/primer-publish/cli.js:29:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
##[error]Docker run failed with exit code 1
```

**Comment by kristfal** [comment]
I'm seeing the same error without passing `--dir`. Did you solve it?

**Comment by erictuvesson** [comment]
I never solved it unfortunately.

**Comment by afeiship** [comment]
The same problem.

**Comment by cinderblock** [comment]
I was able to get the `--dir` option set in Workflows v2 using the [`with.args` option](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepswithargs).

```yml
      - name: Publish
        uses: primer/publish@master
        with:
          args: '--dir=dist'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

However now I'm running into a problem where it thinks I'm not authenticated even though it has my token... #27 

PS. This issue should be renamed to something like "Cannot set --dir option on Workflows V2"

**Comment by ericwooley** [comment]
I think you guys might be missing the checkout step

Full action:
```yml
name: publish
on:
  push:
    branches:
      - '*'
jobs:
  publish-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: primer/publish@master
        env:
          NPM_REGISTRY_URL: registry.npmjs.org
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          args: '--dry-run'
```

EDIT: this doesn't solve the dir problem. Just a solution if you get the `Unable to read package.json` problem.
